### ISSUE TITLE
php不支持

### ISSUE THREAD

**Issue by ssrsec** [leohearts/awd-watchbird#1]
参考：https://www.cnblogs.com/yimingwang/p/13279706.html

像phpmyadmin5.0.2要求php7，而且第一行都是declare(strict_types=1);，如果waf引用加在第一行就报错了，建议判断有无declare(strict_types=1);，有的话就加在下面

**Comment by leohearts** [comment]
是这样。之前判断的还有namespace这种也不能放在第一行，感谢指出。On Aug 28, 2020 10:13 PM, 说书人 <notifications@github.com> wrote:

参考：https://www.cnblogs.com/yimingwang/p/13279706.html

像phpmyadmin5.0.2要求php7，而且第一行都是declare(strict_types=1);，如果waf引用加在第一行就报错了，建议判断有无declare(strict_types=1);，有的话就加在下面

**Comment by ssrsec** [comment]
您好，请问有计划更新到php7支持吗

**Comment by leohearts** [comment]
我想它是支持php7的On Aug 29, 2020 1:25 PM, 说书人 <notifications@github.com> wrote:

您好，请问有计划更新到php7支持吗
