### ISSUE TITLE
resonse_content防护时的flag

### ISSUE THREAD

**Issue by tysmlq** [leohearts/awd-watchbird#10]
开启response_content_match时，页面返回假flag，如flag{5hM4x6YBlCRfTZ2edqvNrLgFmD}，虽然在配置页面下已设置了预定flag内容，但此处仍动态显示上面的flag，不知在哪里设置？

**Comment by WAY29** [comment]
根据源码，实际上一共有2个假flag，其中一个是黑名单拦截生成的随机flag，一个是response_content_match匹配到时显示的配置flag，所以你设置的是第二个flag，而因为你被黑名单拦截了所以显示的是第一个随机生成的flag

**Comment by WAY29** [comment]
如果你想更改的话可以直接修改源码，源码很简单。
