### ISSUE TITLE
反复出现设置初始密码

### ISSUE THREAD

**Issue by Oceanlotus** [leohearts/awd-watchbird#2]
无法正常登录，一直卡在设置初始密码处。
nginx/1.18.0  PHP 5.6.40

**Comment by leohearts** [comment]
你可能安装时不小心没有打/打错了--install命令用ctf权限运行过一次，导致www-data无法写/tmp/watchbird尝试删除/tmp/watchbird另一种可能，www-data无法访问/tmp或存在open_basedir(不太可能)On Oct 29, 2020 7:23 PM, Oceanlotus <notifications@github.com> wrote:

无法正常登录，一直卡在设置初始密码处。

nginx/1.18.0  PHP 5.6.40

**Comment by Oceanlotus** [comment]
的确是没有/tmp权限导致的，环境配置的有点小问题。
