### ISSUE TITLE
本地发包问题

### ISSUE THREAD

**Issue by nniujun** [leohearts/awd-watchbird#4]
大佬好，我使用了本地发包，但是抓包发现并没有从本地发包，求大佬指点。

**Comment by leohearts** [comment]
这个功能是使用位于localhost:80的watchbird.php来发包, 以替换默认的使用自己的靶机发包.
并不是用浏览器发包的. (因浏览器同源策略的缘故做不到, 所以本地发包也是用watchbird.php后端, 只是换成了本地后端)

**Comment by nniujun** [comment]
我在本地服务器根目录上传了watchbird.php，用wireshark抓包没有看到本地服务器发包出去，本地服务器kali,组网方式nat，疑惑~

**Comment by nniujun** [comment]
> 这个功能是使用位于localhost:80的watchbird.php来发包, 以替换默认的使用自己的靶机发包.
> 并不是用浏览器发包的. (因浏览器同源策略的缘故做不到, 所以本地发包也是用watchbird.php后端, 只是换成了本地后端)

是不是需要在配置页面把remoteip改为本地服务器的地址呢

**Comment by nniujun** [comment]
> > 这个功能是使用位于localhost:80的watchbird.php来发包, 以替换默认的使用自己的靶机发包.
> > 并不是用浏览器发包的. (因浏览器同源策略的缘故做不到, 所以本地发包也是用watchbird.php后端, 只是换成了本地后端)
> 
> 是不是需要在配置页面把remoteip改为本地服务器的地址呢

我在本地服务器根目录上传了watchbird.php，用wireshark抓包没有看到本地服务器发包出去，本地服务器kali,组网方式nat，疑惑

**Comment by leohearts** [comment]
> > > 这个功能是使用位于localhost:80的watchbird.php来发包, 以替换默认的使用自己的靶机发包.
> > > 并不是用浏览器发包的. (因浏览器同源策略的缘故做不到, 所以本地发包也是用watchbird.php后端, 只是换成了本地后端)
> > 
> > 
> > 是不是需要在配置页面把remoteip改为本地服务器的地址呢
> 
> 我在本地服务器根目录上传了watchbird.php，用wireshark抓包没有看到本地服务器发包出去，本地服务器kali,组网方式nat，疑惑

![image](https://user-images.githubusercontent.com/24632029/131431668-e609b494-a1d0-43e0-8432-5c773fe6b3bb.png)
勾选这个就可以了呀
![image](https://user-images.githubusercontent.com/24632029/131431826-85db59aa-1ee3-45c9-b01b-11b9c5266468.png)

**Comment by nniujun** [comment]
> > > > 这个功能是使用位于localhost:80的watchbird.php来发包, 以替换默认的使用自己的靶机发包.
> > > > 并不是用浏览器发包的. (因浏览器同源策略的缘故做不到, 所以本地发包也是用watchbird.php后端, 只是换成了本地后端)
> > > 
> > > 
> > > 是不是需要在配置页面把remoteip改为本地服务器的地址呢
> > 
> > 
> > 我在本地服务器根目录上传了watchbird.php，用wireshark抓包没有看到本地服务器发包出去，本地服务器kali,组网方式nat，疑惑
> 
> ![image](https://user-images.githubusercontent.com/24632029/131431668-e609b494-a1d0-43e0-8432-5c773fe6b3bb.png)
> 勾选这个就可以了呀
> ![image](https://user-images.githubusercontent.com/24632029/131431826-85db59aa-1ee3-45c9-b01b-11b9c5266468.png)
![Snipaste_2021-08-31_10-48-57](https://user-images.githubusercontent.com/14218211/131434121-b3a16713-d4c2-4e43-8af0-fb11de25db96.png)

**Comment by nniujun** [comment]
> > > > > 这个功能是使用位于localhost:80的watchbird.php来发包, 以替换默认的使用自己的靶机发包.
> > > > > 并不是用浏览器发包的. (因浏览器同源策略的缘故做不到, 所以本地发包也是用watchbird.php后端, 只是换成了本地后端)
> > > > 
> > > > 
> > > > 是不是需要在配置页面把remoteip改为本地服务器的地址呢
> > > 
> > > 
> > > 我在本地服务器根目录上传了watchbird.php，用wireshark抓包没有看到本地服务器发包出去，本地服务器kali,组网方式nat，疑惑
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/24632029/131431668-e609b494-a1d0-43e0-8432-5c773fe6b3bb.png)
> > 勾选这个就可以了呀
> > ![image](https://user-images.githubusercontent.com/24632029/131431826-85db59aa-1ee3-45c9-b01b-11b9c5266468.png)
> > ![Snipaste_2021-08-31_10-48-57](https://user-images.githubusercontent.com/14218211/131434121-b3a16713-d4c2-4e43-8af0-fb11de25db96.png)

**Comment by nniujun** [comment]
> > > > > > 这个功能是使用位于localhost:80的watchbird.php来发包, 以替换默认的使用自己的靶机发包.
> > > > > > 并不是用浏览器发包的. (因浏览器同源策略的缘故做不到, 所以本地发包也是用watchbird.php后端, 只是换成了本地后端)
> > > > > 
> > > > > 
> > > > > 是不是需要在配置页面把remoteip改为本地服务器的地址呢
> > > > 
> > > > 
> > > > 我在本地服务器根目录上传了watchbird.php，用wireshark抓包没有看到本地服务器发包出去，本地服务器kali,组网方式nat，疑惑
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/24632029/131431668-e609b494-a1d0-43e0-8432-5c773fe6b3bb.png)
> > > 勾选这个就可以了呀
> > > ![image](https://user-images.githubusercontent.com/24632029/131431826-85db59aa-1ee3-45c9-b01b-11b9c5266468.png)
> > > ![Snipaste_2021-08-31_10-48-57](https://user-images.githubusercontent.com/14218211/131434121-b3a16713-d4c2-4e43-8af0-fb11de25db96.png)
大佬，我测试了下，看到是本地发包到远程服务器，远程服务器再发包到配置的flag接收ip地址，127.00.1:8080->10,177.228.72:80->192.168.100.128:9090

**Comment by nniujun** [comment]
> > > > > > > 这个功能是使用位于localhost:80的watchbird.php来发包, 以替换默认的使用自己的靶机发包.
> > > > > > > 并不是用浏览器发包的. (因浏览器同源策略的缘故做不到, 所以本地发包也是用watchbird.php后端, 只是换成了本地后端)
> > > > > > 
> > > > > > 
> > > > > > 是不是需要在配置页面把remoteip改为本地服务器的地址呢
> > > > > 
> > > > > 
> > > > > 我在本地服务器根目录上传了watchbird.php，用wireshark抓包没有看到本地服务器发包出去，本地服务器kali,组网方式nat，疑惑
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/24632029/131431668-e609b494-a1d0-43e0-8432-5c773fe6b3bb.png)
> > > > 勾选这个就可以了呀
> > > > ![image](https://user-images.githubusercontent.com/24632029/131431826-85db59aa-1ee3-45c9-b01b-11b9c5266468.png)
> > > > ![Snipaste_2021-08-31_10-48-57](https://user-images.githubusercontent.com/14218211/131434121-b3a16713-d4c2-4e43-8af0-fb11de25db96.png)
> > > > 大佬，我测试了下，看到是本地发包到远程服务器，远程服务器再发包到配置的flag接收ip地址，127.00.1:8080->10,177.228.72:80->192.168.100.128:9090

我懂大佬的意思了，应该是说payload是从本地发包的，我理解为配置后自动提交flag的包从本地发包。大佬，能不能flag提交也从本地发包呢

**Comment by leohearts** [comment]
哦！本来应该是这样设计的，我看看是不是哪里出了bug
On Aug 31, 2021 11:11 AM, nniujun ***@***.***> wrote:







这个功能是使用位于localhost:80的watchbird.php来发包, 以替换默认的使用自己的靶机发包.
并不是用浏览器发包的. (因浏览器同源策略的缘故做不到, 所以本地发包也是用watchbird.php后端, 只是换成了本地后端)

是不是需要在配置页面把remoteip改为本地服务器的地址呢

我在本地服务器根目录上传了watchbird.php，用wireshark抓包没有看到本地服务器发包出去，本地服务器kali,组网方式nat，疑惑


勾选这个就可以了呀


大佬，我测试了下，看到是本地发包到远程服务器，远程服务器再发包到配置的flag接收ip地址，127.00.1:8080->10,177.228.72:80->192.168.100.128:9090




我懂大佬的意思了，应该是说payload是从本地发包的，我理解为配置后自动提交flag的包从本地发包。大佬，能不能flag提交也从本地发包呢

**Comment by nniujun** [comment]
> 哦！本来应该是这样设计的，我看看是不是哪里出了bug On Aug 31, 2021 11:11 AM, nniujun ***@***.***> wrote: 这个功能是使用位于localhost:80的watchbird.php来发包, 以替换默认的使用自己的靶机发包. 并不是用浏览器发包的. (因浏览器同源策略的缘故做不到, 所以本地发包也是用watchbird.php后端, 只是换成了本地后端) 是不是需要在配置页面把remoteip改为本地服务器的地址呢 我在本地服务器根目录上传了watchbird.php，用wireshark抓包没有看到本地服务器发包出去，本地服务器kali,组网方式nat，疑惑 勾选这个就可以了呀 大佬，我测试了下，看到是本地发包到远程服务器，远程服务器再发包到配置的flag接收ip地址，127.00.1:8080->10,177.228.72:80->192.168.100.128:9090 我懂大佬的意思了，应该是说payload是从本地发包的，我理解为配置后自动提交flag的包从本地发包。大佬，能不能flag提交也从本地发包呢 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

感谢大佬

**Comment by nniujun** [comment]
> 哦！本来应该是这样设计的，我看看是不是哪里出了bug On Aug 31, 2021 11:11 AM, nniujun ***@***.***> wrote: 这个功能是使用位于localhost:80的watchbird.php来发包, 以替换默认的使用自己的靶机发包. 并不是用浏览器发包的. (因浏览器同源策略的缘故做不到, 所以本地发包也是用watchbird.php后端, 只是换成了本地后端) 是不是需要在配置页面把remoteip改为本地服务器的地址呢 我在本地服务器根目录上传了watchbird.php，用wireshark抓包没有看到本地服务器发包出去，本地服务器kali,组网方式nat，疑惑 勾选这个就可以了呀 大佬，我测试了下，看到是本地发包到远程服务器，远程服务器再发包到配置的flag接收ip地址，127.00.1:8080->10,177.228.72:80->192.168.100.128:9090 我懂大佬的意思了，应该是说payload是从本地发包的，我理解为配置后自动提交flag的包从本地发包。大佬，能不能flag提交也从本地发包呢 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

一直盼着大佬更新~

**Comment by nniujun** [comment]
大佬，刚才测试了下，直接自动提交flag没有包发出去了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Leohearts ***@***.***&gt;
发送时间: 2021年8月31日 17:34
收件人: leohearts/awd-watchbird ***@***.***&gt;
抄送: nniujun ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[leohearts/awd-watchbird] 本地发包问题 (#4)





 
Closed #4 via fd2b33a.
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leohearts** [comment]
What 我commit前是有测试了的…方便截个控制台报错的图吗
On Aug 31, 2021 6:46 PM, nniujun ***@***.***> wrote:

大佬，刚才测试了下，直接自动提交flag没有包发出去了











发自我的iPhone







------------------ 原始邮件 ------------------



发件人: Leohearts ***@***.***&gt;



发送时间: 2021年8月31日 17:34



收件人: leohearts/awd-watchbird ***@***.***&gt;



抄送: nniujun ***@***.***&gt;, State change ***@***.***&gt;



主题: 回复：[leohearts/awd-watchbird] 本地发包问题 (#4)























 



Closed #4 via fd2b33a.



 



—



You are receiving this because you modified the open/close state.



Reply to this email directly, view it on GitHub, or unsubscribe.



Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nniujun** [comment]
大佬，能加微信不，我微信号[REDACTED]，或者大佬给个您的微信

**Comment by leohearts** [comment]
> 大佬，能加微信不，我微信号[REDACTED]，或者大佬给个您的微信

算了吧，还是不要自我出道比较好哦😂
在这里公开讨论也有利于后续的维护。

**Comment by nniujun** [comment]
好勒，


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Leohearts ***@***.***&gt;
发送时间: 2021年8月31日 18:57
收件人: leohearts/awd-watchbird ***@***.***&gt;
抄送: nniujun ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[leohearts/awd-watchbird] 本地发包问题 (#4)





  
大佬，能加微信不，我微信号514792669，或者大佬给个您的微信
  
算了吧，还是不要自我出道比较好哦😂
 在这里公开讨论也有利于后续的维护。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
