### ISSUE TITLE
最新版本地发包问题

### ISSUE THREAD

**Issue by nniujun** [leohearts/awd-watchbird#5]
大佬，编译并使用了最新的程序，发现本地flag自动提交没有包发出去，请大佬指点~
![1](https://user-images.githubusercontent.com/14218211/131490475-3f6e5ceb-aaa8-4b79-bd6c-488766c2623c.png)

**Comment by leohearts** [comment]
你看右边，并没有匹配识别出flag
你可以修改一下flag正则，比如 flag\{.* ，或者关掉防护😂
它被watchbird拦截了吧。

**Comment by nniujun** [comment]
确实，感谢大佬，我也在成都，我们正在准备比赛，大佬要是想讲课可以给我说哈。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Leohearts ***@***.***&gt;
发送时间: 2021年8月31日 19:03
收件人: leohearts/awd-watchbird ***@***.***&gt;
抄送: nniujun ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[leohearts/awd-watchbird]最新版本地发包问题 (#5)





 
你看右边，并没有匹配识别出flag
 你可以修改一下flag正则，或者关掉防护😂
 它被watchbird拦截了吧。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leohearts** [comment]
> 确实，感谢大佬，我也在成都，我们正在准备比赛，大佬要是想讲课可以给我说哈。
> 
> 
> 发自我的iPhone
> 
> ------------------ 原始邮件 ------------------
> 发件人: Leohearts ***@***.***&gt;
> 发送时间: 2021年8月31日 19:03
> 收件人: leohearts/awd-watchbird ***@***.***&gt;
> 抄送: nniujun ***@***.***&gt;, State change ***@***.***&gt;
> 主题: 回复：[leohearts/awd-watchbird]最新版本地发包问题 (#5)
> 
> 
> 
> 
> 
>  
> 你看右边，并没有匹配识别出flag
>  你可以修改一下flag正则，或者关掉防护😂
>  它被watchbird拦截了吧。
>  
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.

好哦，如果有需求的话可以联系邮件 leohearts@leohearts.com ，乐意协助👍

**Comment by nniujun** [comment]
还有个小问题，发送出去的flag字符串被url编码了，比如”{“被编码为%7B

**Comment by leohearts** [comment]
> 还有个小问题，发送出去的flag字符串被url编码了，比如”{“被编码为%7B

诶，是出了什么问题吗
按理说对于urlencoded格式的包应该是正确操作？
还是说你是用json，这个可能没有充分测试

**Comment by leohearts** [comment]
> 还有个小问题，发送出去的flag字符串被url编码了，比如”{“被编码为%7B

![Screenshot_20210831-192631096.jpg](https://user-images.githubusercontent.com/24632029/131494657-25164e32-4164-430f-846c-f215eb1501c5.jpg)
看起来代码应该没有问题，如果不需要url编码可以把包里的content-type改掉，比如json就是application/json。
默认提交flag包是用的x-www-form-urlencoded，这样的情况下编码应该是正确的实现。

**Comment by nniujun** [comment]
> > 还有个小问题，发送出去的flag字符串被url编码了，比如”{“被编码为%7B
> 
> 诶，是出了什么问题吗
> 按理说对于urlencoded格式的包应该是正确操作？
> 还是说你是用json，这个可能没有充分测试

懂了，谢谢大佬指点

**Comment by nniujun** [comment]
大佬，不好意思这么晚打扰您，刚才我用flag自动提交功能一直提交flag不成功，抓了下包，发现抓到的数据包长度不正确，导致数据不完整，又要麻烦您看看勒


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Leohearts ***@***.***&gt;
发送时间: 2021年8月31日 19:28
收件人: leohearts/awd-watchbird ***@***.***&gt;
抄送: nniujun ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[leohearts/awd-watchbird] 最新版本地发包问题 (#5)





  
还有个小问题，发送出去的flag字符串被url编码了，比如”{“被编码为%7B
  

 看起来代码应该没有问题，如果不需要url编码可以把包里的content-type改掉，比如json就是application/json。
 默认提交flag包是用的x-www-urlencoded，这样的情况下编码应该是正确的实现。
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leohearts** [comment]
哇。方便截图一下完整包吗？

**Comment by nniujun** [comment]
发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Leohearts ***@***.***&gt;
发送时间: 2021年8月31日 21:52
收件人: leohearts/awd-watchbird ***@***.***&gt;
抄送: nniujun ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[leohearts/awd-watchbird]最新版本地发包问题 (#5)





 
哇。方便截图一下完整包吗？
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nniujun** [comment]
> 哇。方便截图一下完整包吗？

![image](https://user-images.githubusercontent.com/14218211/131518608-5131becf-8e2e-49a1-a94d-ae0a08dbecae.png)
![image](https://user-images.githubusercontent.com/14218211/131518673-d36d3bd9-0f46-4f7f-a15f-cc5a13d24380.png)
![image](https://user-images.githubusercontent.com/14218211/131518746-413b88c6-0cc7-4719-9bb1-700ee691f8f4.png)

**Comment by f1312048532** [comment]
为什么1.62版本 无法开启 weblog
