### ISSUE TITLE
控制台没有日志

### ISSUE THREAD

**Issue by Jacker132** [leohearts/awd-watchbird#6]
部署后，能够成功拦截，日志txt文件在/tmp/systemd-private-a4a7987b08fe4cdfa2ac38de34acd45d-php-fpm.service-GoFPNh/tmp/watchbird/log路径下，但是控制台的日志标签内刷新不出来日志，请问是什么原因呢？

**Comment by leohearts** [comment]
截个图看一下？我不太确定是怎么回事，要不检查一下log下几个文件的权限，以及浏览器控制台有没有报错On Dec 14, 2021 9:53 AM, Hussar、longheng ***@***.***> wrote:

部署后，能够成功拦截，日志txt文件在/tmp/systemd-private-a4a7987b08fe4cdfa2ac38de34acd45d-php-fpm.service-GoFPNh/tmp/watchbird/log路径下，但是控制台的日志标签内刷新不出来日志，请问是什么原因呢？

**Comment by Jacker132** [comment]
![image](https://user-images.githubusercontent.com/38522348/145918812-e9b21d9f-a64d-4a02-91ab-a47ca75d1345.png)
![image](https://user-images.githubusercontent.com/38522348/145918829-c043d6c2-2a07-423f-9acd-15bea67446c8.png)

**Comment by Jacker132** [comment]
控制台上是没有报错的，我把整个tmp目录和网站/var/www/html目录都设置了777权限，还是不行，大佬帮忙看下

**Comment by leohearts** [comment]
浏览器F12看一下有没有正确拉取日志？请打开F12网络流量页面, 然后触发一下攻击，看看有没有获取到新日志On Dec 14, 2021 9:58 AM, Hus3ar ***@***.***> wrote:

控制台上是没有报错的，我把整个tmp目录和网站/var/www/html目录都设置了777权限，还是不行，大佬帮忙看下

**Comment by Jacker132** [comment]
这里确实在疯狂的报错
![image](https://user-images.githubusercontent.com/38522348/145919924-9d7356d7-537e-4f76-b757-952e4c2f4013.png)

**Comment by leohearts** [comment]
> 这里确实在疯狂的报错
> ![image](https://user-images.githubusercontent.com/38522348/145919924-9d7356d7-537e-4f76-b757-952e4c2f4013.png)
> 

500 了，你看看apache error log？
检查一下自己的php版本，我看看能不能复现

**Comment by Jacker132** [comment]
access_log:
![image](https://user-images.githubusercontent.com/38522348/145920945-15515b74-d209-4f05-9a19-66a0925062e0.png)
error_log:
![image](https://user-images.githubusercontent.com/38522348/145921044-c6b2cb3c-1ef1-4558-85d7-a93b61023c4d.png)

**Comment by Jacker132** [comment]
php版本
![image](https://user-images.githubusercontent.com/38522348/145921132-0a007aca-5119-4624-a64e-64edb689bb55.png)

**Comment by leohearts** [comment]
现在网站正常页面还工作吗，怀疑是服务器挂了？

**Comment by Jacker132** [comment]
网页都是正常的，还可以正常触发规则，被拦截

**Comment by leohearts** [comment]
> 网页都是正常的，还可以正常触发规则，被拦截

那奇妙，要不你在watchbird.php前面加一句error_reporting(E_ALL)

**Comment by Jacker132** [comment]
加了，但是没有看到报错信息

**Comment by Jacker132** [comment]
而且我这里无法选中自动刷新
![image](https://user-images.githubusercontent.com/38522348/145924741-cfe7a5a3-c8b1-4b97-bbf6-5de533af9a5a.png)

**Comment by Jacker132** [comment]
加了之后，不再报200，应该是报错了，但是报错信息不知道从哪里查看
![image](https://user-images.githubusercontent.com/38522348/145924902-93434b0d-eb87-4685-be7a-95b2d14d05ad.png)

**Comment by leohearts** [comment]
点进去F12的200一项，responseOn Dec 14, 2021 10:59 AM, Hus3ar ***@***.***> wrote:

加了之后，不再报200，应该是报错了，但是报错信息不知道从哪里查看

**Comment by Jacker132** [comment]
![image](https://user-images.githubusercontent.com/38522348/145925953-5a1f1dee-f41b-4f52-bb97-6c5a35283426.png)
![image](https://user-images.githubusercontent.com/38522348/145925897-1c615617-5e21-439c-a113-35ccaf599cc1.png)

**Comment by Jacker132** [comment]
我仔细阅读了代码，我已经找到原因了，经过测试，watchbird已经部署成功了，并且记录访问日志，虽然代码中将日志保存在/tmp目录下，也成功保存了。但是linux为了安全性，只要使用Systemd这个进程作为启动进程的linux系统，其子进程都会有PrivateTmp属性，用于设置是否使用私有的tmp目录。只要设置使用这个属性的service，都会使用私有的tmp目录，虽然操作的对象是/tmp/xxx，但是实际放在linux的目录却是/tmp/systemd-private-xxxxx-php-fpm.service/xxx，会导致服务异常：
![image](https://user-images.githubusercontent.com/38522348/146170064-4dbc2a32-2d7b-40e3-a2c5-fb946dea8a88.png)
所以需要修改php-fpm.service的PrivateTmp属性为false，并重启php-fpm服务，这样就会将文件直接保存在tmp目录下：
![image](https://user-images.githubusercontent.com/38522348/146170456-4cd622dc-2bd6-4c41-b483-d2173dd21a91.png)
并且页面也能够正常显示信息：
![image](https://user-images.githubusercontent.com/38522348/146170681-5c354401-4e85-4b8f-b780-01b929d12626.png)

**Comment by Jacker132** [comment]
修改php-fpm.service文件（unit）后，重载unit文件：systemctl daemon-reload，最后重启php-fpm服务，即可正常使用tmp。

**Comment by leohearts** [comment]
OK. 不过我测试的环境也开了private tmp, log保存在了私有tmp下依然可用我回去再测试一下是怎么回事吧，谢谢反馈On Dec 15, 2021 6:37 PM, Hus3ar ***@***.***> wrote:

修改php-fpm.service文件（unit）后，重载unit文件：systemctl daemon-reload，最后重启php-fpm服务，即可正常使用tmp。

**Comment by Jacker132** [comment]
好的。

**Comment by Jacker132** [comment]
还有个小建议，对于控制台的路径可以添加个随机的路径，否则会存在一点点的安全性问题

**Comment by leohearts** [comment]
> 还有个小建议，对于控制台的路径可以添加个随机的路径，否则会存在一点点的安全性问题

嗯嗯，谢谢建议
不过感觉有密码的话也算OK, 如果要防检测的话需要改掉一大堆路由

**Comment by Jacker132** [comment]
好的
