### ISSUE TITLE
部署waf后对一句话shell可以拦截，但过一会儿就无效了

### ISSUE THREAD

**Issue by tysmlq** [leohearts/awd-watchbird#7]
通过php watchbird.php --install /var/www/html 可以成功部署waf
利用一句话shell来测试waf，访问shell.php并执行system命令可以被waf拦截，且同时在waf log中可以看到执行的指令
但对shell执行几次命令后，再去访问shell，发现不再拦截，且之前写入shell的<?php include_once 'watchbird.php'?>已经没有了
连续试了多次都这样，不知什么原因？

**Comment by leohearts** [comment]
情况有一点迷惑，你是不是开了不死马/文件保护之类的？ Watchbird在安装好后不会修改文件，可以检查一下是不是有别的程序在碰你的文件On Jan 1, 2022 10:24 PM, tysmlq ***@***.***> wrote:

通过php watchbird.php --install /var/www/html 可以成功部署waf

利用一句话shell来测试waf，访问shell.php并执行system命令可以被waf拦截，且同时在waf log中可以看到执行的指令

但对shell执行几次命令后，再去访问shell，发现不再拦截，且之前写入shell的已经没有了

连续试了多次都这样，不知什么原因？

**Comment by tysmlq** [comment]
抱歉，检查了一下，确实有一个循环脚本在覆盖shell，waf没问题。
另外，为何在index.php中插入include waf语句后，页面会无法显示？即使手工删除这行也没用

**Comment by leohearts** [comment]
可能你使用的网站程序的 index.php 依赖了其他 php 文件，其中依然存在watchbird，实际上还是已经安装了。页面失败可能是因为 watchbird 修改了不应该修改的文件，造成了php语法错误，或你的环境不支持 watchbird。你可以尝试：- 查看 php 错误日志- 访问 index.php?watchbird=ui 看看是否可以正常运行 watchbird，如果可以正确进入控制台，尝试关闭所有防护选项后再访问网站。On Jan 2, 2022 8:51 AM, tysmlq ***@***.***> wrote:

抱歉，检查了一下，确实有一个循环脚本在覆盖shell，waf没问题。

另外，为何在index.php中插入include waf语句后，页面会无法显示？即使手工删除这行也没用

**Comment by tysmlq** [comment]
明白了，感谢！
